# Form implementation generated from reading ui file '.\editar_matricula_2.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 747)
        MainWindow.setMaximumSize(QtCore.QSize(1980, 1080))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(243, 230, 213);")
        MainWindow.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 721, 521))
        self.scrollArea.setStyleSheet("QScrollBar{ background-color: rgb(203, 132, 0);; \n"
"color: rgb(243, 230, 213);\n"
"} ")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 702, 1271))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.id_aluno = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents_2)
        self.id_aluno.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(12)
        self.id_aluno.setFont(font)
        self.id_aluno.setStyleSheet("color: rgb(203, 132, 0);")
        self.id_aluno.setObjectName("id_aluno")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.id_aluno)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nome_aluno = QtWidgets.QLineEdit(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_aluno.setFont(font)
        self.nome_aluno.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 14px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.nome_aluno.setMaxLength(255)
        self.nome_aluno.setClearButtonEnabled(True)
        self.nome_aluno.setObjectName("nome_aluno")
        self.verticalLayout_3.addWidget(self.nome_aluno)
        self.codigo_NIS = QtWidgets.QLineEdit(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.codigo_NIS.setFont(font)
        self.codigo_NIS.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 14px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.codigo_NIS.setMaxLength(255)
        self.codigo_NIS.setClearButtonEnabled(True)
        self.codigo_NIS.setObjectName("codigo_NIS")
        self.verticalLayout_3.addWidget(self.codigo_NIS)
        self.label_id_racial = QtWidgets.QLabel(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_id_racial.setFont(font)
        self.label_id_racial.setStyleSheet("color: rgb(203, 132, 0);\n"
"font: 57 10pt \"Inter Medium\";")
        self.label_id_racial.setObjectName("label_id_racial")
        self.verticalLayout_3.addWidget(self.label_id_racial)
        self.sel_id_racial = QtWidgets.QComboBox(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_id_racial.setFont(font)
        self.sel_id_racial.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_id_racial.setObjectName("sel_id_racial")
        self.sel_id_racial.addItem("")
        self.sel_id_racial.addItem("")
        self.sel_id_racial.addItem("")
        self.sel_id_racial.addItem("")
        self.sel_id_racial.addItem("")
        self.sel_id_racial.addItem("")
        self.verticalLayout_3.addWidget(self.sel_id_racial)
        self.label_sexo = QtWidgets.QLabel(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_sexo.setFont(font)
        self.label_sexo.setStyleSheet("color: rgb(203, 132, 0);font: 57 10pt \"Inter Medium\";")
        self.label_sexo.setObjectName("label_sexo")
        self.verticalLayout_3.addWidget(self.label_sexo)
        self.sel_sexo = QtWidgets.QComboBox(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_sexo.setFont(font)
        self.sel_sexo.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_sexo.setObjectName("sel_sexo")
        self.sel_sexo.addItem("")
        self.sel_sexo.addItem("")
        self.sel_sexo.addItem("")
        self.verticalLayout_3.addWidget(self.sel_sexo)
        self.nascimento_uf = QtWidgets.QLineEdit(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nascimento_uf.setFont(font)
        self.nascimento_uf.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.nascimento_uf.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.nascimento_uf.setText("")
        self.nascimento_uf.setMaxLength(2)
        self.nascimento_uf.setClearButtonEnabled(False)
        self.nascimento_uf.setObjectName("nascimento_uf")
        self.verticalLayout_3.addWidget(self.nascimento_uf)
        self.nascimento_municipio = QtWidgets.QLineEdit(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nascimento_municipio.setFont(font)
        self.nascimento_municipio.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.nascimento_municipio.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.nascimento_municipio.setText("")
        self.nascimento_municipio.setMaxLength(30)
        self.nascimento_municipio.setClearButtonEnabled(False)
        self.nascimento_municipio.setObjectName("nascimento_municipio")
        self.verticalLayout_3.addWidget(self.nascimento_municipio)
        self.label_certidao_civil = QtWidgets.QLabel(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_certidao_civil.setFont(font)
        self.label_certidao_civil.setStyleSheet("color: rgb(45, 84, 60);\n"
"font: 57 10pt \"Inter Medium\";")
        self.label_certidao_civil.setObjectName("label_certidao_civil")
        self.verticalLayout_3.addWidget(self.label_certidao_civil)
        self.sel_certidao_civil = QtWidgets.QComboBox(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_certidao_civil.setFont(font)
        self.sel_certidao_civil.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_certidao_civil.setObjectName("sel_certidao_civil")
        self.sel_certidao_civil.addItem("")
        self.sel_certidao_civil.addItem("")
        self.sel_certidao_civil.addItem("")
        self.verticalLayout_3.addWidget(self.sel_certidao_civil)
        self.certidao_antiga = QtWidgets.QGroupBox(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.certidao_antiga.setFont(font)
        self.certidao_antiga.setObjectName("certidao_antiga")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.certidao_antiga)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.numero_termo = QtWidgets.QLineEdit(parent=self.certidao_antiga)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(11)
        self.numero_termo.setFont(font)
        self.numero_termo.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"color: black\n"
"\n"
"")
        self.numero_termo.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.numero_termo.setMaxLength(8)
        self.numero_termo.setClearButtonEnabled(False)
        self.numero_termo.setObjectName("numero_termo")
        self.horizontalLayout_5.addWidget(self.numero_termo)
        self.livro = QtWidgets.QLineEdit(parent=self.certidao_antiga)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(11)
        self.livro.setFont(font)
        self.livro.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"color: black\n"
"\n"
"")
        self.livro.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.livro.setMaxLength(8)
        self.livro.setClearButtonEnabled(False)
        self.livro.setObjectName("livro")
        self.horizontalLayout_5.addWidget(self.livro)
        self.folha = QtWidgets.QLineEdit(parent=self.certidao_antiga)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(11)
        self.folha.setFont(font)
        self.folha.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"color: black\n"
"\n"
"")
        self.folha.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.folha.setMaxLength(4)
        self.folha.setClearButtonEnabled(False)
        self.folha.setObjectName("folha")
        self.horizontalLayout_5.addWidget(self.folha)
        self.label_data_exp_certidao = QtWidgets.QLabel(parent=self.certidao_antiga)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.label_data_exp_certidao.setFont(font)
        self.label_data_exp_certidao.setStyleSheet("color: rgb(203, 132, 0);")
        self.label_data_exp_certidao.setWordWrap(True)
        self.label_data_exp_certidao.setObjectName("label_data_exp_certidao")
        self.horizontalLayout_5.addWidget(self.label_data_exp_certidao)
        self.data_expedicao = QtWidgets.QDateEdit(parent=self.certidao_antiga)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(12)
        self.data_expedicao.setFont(font)
        self.data_expedicao.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"color: black\n"
"\n"
"")
        self.data_expedicao.setCalendarPopup(True)
        self.data_expedicao.setObjectName("data_expedicao")
        self.horizontalLayout_5.addWidget(self.data_expedicao)
        self.verticalLayout_3.addWidget(self.certidao_antiga)
        self.certidao_nova = QtWidgets.QGroupBox(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.certidao_nova.setFont(font)
        self.certidao_nova.setObjectName("certidao_nova")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.certidao_nova)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.numero_registro_civil = QtWidgets.QLineEdit(parent=self.certidao_nova)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(11)
        self.numero_registro_civil.setFont(font)
        self.numero_registro_civil.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"color: black\n"
"\n"
"")
        self.numero_registro_civil.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.numero_registro_civil.setMaxLength(255)
        self.numero_registro_civil.setCursorPosition(0)
        self.numero_registro_civil.setClearButtonEnabled(False)
        self.numero_registro_civil.setObjectName("numero_registro_civil")
        self.horizontalLayout_6.addWidget(self.numero_registro_civil)
        self.verticalLayout_3.addWidget(self.certidao_nova)
        self.info_documentos = QtWidgets.QGroupBox(parent=self.id_aluno)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.info_documentos.setFont(font)
        self.info_documentos.setStyleSheet("")
        self.info_documentos.setObjectName("info_documentos")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.info_documentos)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_data_exp_info_doc = QtWidgets.QLabel(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(12)
        self.label_data_exp_info_doc.setFont(font)
        self.label_data_exp_info_doc.setStyleSheet("color: rgb(203, 132, 0);\n"
"")
        self.label_data_exp_info_doc.setWordWrap(True)
        self.label_data_exp_info_doc.setObjectName("label_data_exp_info_doc")
        self.gridLayout_4.addWidget(self.label_data_exp_info_doc, 3, 1, 1, 1)
        self.cpf_aluno = QtWidgets.QLineEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cpf_aluno.setFont(font)
        self.cpf_aluno.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.cpf_aluno.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.cpf_aluno.setText("")
        self.cpf_aluno.setMaxLength(15)
        self.cpf_aluno.setClearButtonEnabled(False)
        self.cpf_aluno.setObjectName("cpf_aluno")
        self.gridLayout_4.addWidget(self.cpf_aluno, 4, 0, 1, 1)
        self.documento_tipo = QtWidgets.QLineEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.documento_tipo.setFont(font)
        self.documento_tipo.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.documento_tipo.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.documento_tipo.setText("")
        self.documento_tipo.setMaxLength(30)
        self.documento_tipo.setClearButtonEnabled(False)
        self.documento_tipo.setObjectName("documento_tipo")
        self.gridLayout_4.addWidget(self.documento_tipo, 3, 0, 1, 1)
        self.data_exp = QtWidgets.QDateEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(12)
        self.data_exp.setFont(font)
        self.data_exp.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"color: black\n"
"\n"
"")
        self.data_exp.setCalendarPopup(True)
        self.data_exp.setObjectName("data_exp")
        self.gridLayout_4.addWidget(self.data_exp, 4, 1, 1, 1)
        self.cartorio_nome = QtWidgets.QLineEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cartorio_nome.setFont(font)
        self.cartorio_nome.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.cartorio_nome.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.cartorio_nome.setText("")
        self.cartorio_nome.setMaxLength(30)
        self.cartorio_nome.setClearButtonEnabled(False)
        self.cartorio_nome.setObjectName("cartorio_nome")
        self.gridLayout_4.addWidget(self.cartorio_nome, 2, 1, 1, 1)
        self.cartorio_uf = QtWidgets.QLineEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cartorio_uf.setFont(font)
        self.cartorio_uf.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.cartorio_uf.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.cartorio_uf.setText("")
        self.cartorio_uf.setMaxLength(2)
        self.cartorio_uf.setClearButtonEnabled(False)
        self.cartorio_uf.setObjectName("cartorio_uf")
        self.gridLayout_4.addWidget(self.cartorio_uf, 0, 0, 1, 1)
        self.documento_orgao_emissor = QtWidgets.QLineEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.documento_orgao_emissor.setFont(font)
        self.documento_orgao_emissor.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.documento_orgao_emissor.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.documento_orgao_emissor.setText("")
        self.documento_orgao_emissor.setMaxLength(2)
        self.documento_orgao_emissor.setClearButtonEnabled(False)
        self.documento_orgao_emissor.setObjectName("documento_orgao_emissor")
        self.gridLayout_4.addWidget(self.documento_orgao_emissor, 0, 1, 1, 1)
        self.cartorio_municipio = QtWidgets.QLineEdit(parent=self.info_documentos)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cartorio_municipio.setFont(font)
        self.cartorio_municipio.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.cartorio_municipio.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.cartorio_municipio.setText("")
        self.cartorio_municipio.setMaxLength(30)
        self.cartorio_municipio.setClearButtonEnabled(False)
        self.cartorio_municipio.setObjectName("cartorio_municipio")
        self.gridLayout_4.addWidget(self.cartorio_municipio, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.info_documentos)
        self.verticalLayout_4.addWidget(self.id_aluno)
        self.InformacoesdeMatricula = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.InformacoesdeMatricula.setFont(font)
        self.InformacoesdeMatricula.setStyleSheet("color: rgb(203, 132, 0);")
        self.InformacoesdeMatricula.setObjectName("InformacoesdeMatricula")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.InformacoesdeMatricula)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.nome_escola = QtWidgets.QLineEdit(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_escola.setFont(font)
        self.nome_escola.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.nome_escola.setMaxLength(255)
        self.nome_escola.setClearButtonEnabled(True)
        self.nome_escola.setObjectName("nome_escola")
        self.gridLayout_5.addWidget(self.nome_escola, 0, 0, 1, 8)
        self.serie_label = QtWidgets.QLabel(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.serie_label.setFont(font)
        self.serie_label.setStyleSheet("color: rgb(203, 132, 0);")
        self.serie_label.setObjectName("serie_label")
        self.gridLayout_5.addWidget(self.serie_label, 4, 1, 1, 1)
        self.procedencia_label = QtWidgets.QLabel(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.procedencia_label.setFont(font)
        self.procedencia_label.setStyleSheet("color: rgb(203, 132, 0);")
        self.procedencia_label.setObjectName("procedencia_label")
        self.gridLayout_5.addWidget(self.procedencia_label, 4, 2, 1, 1)
        self.bolsa_familia = QtWidgets.QCheckBox(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bolsa_familia.setFont(font)
        self.bolsa_familia.setStyleSheet("\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.bolsa_familia.setObjectName("bolsa_familia")
        self.gridLayout_5.addWidget(self.bolsa_familia, 4, 5, 1, 1)
        self.sel_serie = QtWidgets.QComboBox(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_serie.setFont(font)
        self.sel_serie.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_serie.setObjectName("sel_serie")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.sel_serie.addItem("")
        self.gridLayout_5.addWidget(self.sel_serie, 5, 1, 1, 1)
        self.turno_label = QtWidgets.QLabel(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.turno_label.setFont(font)
        self.turno_label.setStyleSheet("color: rgb(203, 132, 0);")
        self.turno_label.setObjectName("turno_label")
        self.gridLayout_5.addWidget(self.turno_label, 4, 0, 1, 1)
        self.transporte = QtWidgets.QCheckBox(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.transporte.setFont(font)
        self.transporte.setStyleSheet("\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.transporte.setObjectName("transporte")
        self.gridLayout_5.addWidget(self.transporte, 5, 5, 1, 1)
        self.sel_turno = QtWidgets.QComboBox(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_turno.setFont(font)
        self.sel_turno.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_turno.setObjectName("sel_turno")
        self.sel_turno.addItem("")
        self.sel_turno.addItem("")
        self.sel_turno.addItem("")
        self.sel_turno.addItem("")
        self.sel_turno.addItem("")
        self.gridLayout_5.addWidget(self.sel_turno, 5, 0, 1, 1)
        self.sel_procedencia = QtWidgets.QComboBox(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_procedencia.setFont(font)
        self.sel_procedencia.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_procedencia.setObjectName("sel_procedencia")
        self.sel_procedencia.addItem("")
        self.sel_procedencia.addItem("")
        self.sel_procedencia.addItem("")
        self.sel_procedencia.addItem("")
        self.sel_procedencia.addItem("")
        self.sel_procedencia.addItem("")
        self.gridLayout_5.addWidget(self.sel_procedencia, 5, 2, 1, 3)
        self.codigo_inep = QtWidgets.QLineEdit(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.codigo_inep.setFont(font)
        self.codigo_inep.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.codigo_inep.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.codigo_inep.setText("")
        self.codigo_inep.setMaxLength(8)
        self.codigo_inep.setClearButtonEnabled(False)
        self.codigo_inep.setObjectName("codigo_inep")
        self.gridLayout_5.addWidget(self.codigo_inep, 2, 0, 1, 3)
        self.codigo_turma = QtWidgets.QLineEdit(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.codigo_turma.setFont(font)
        self.codigo_turma.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.codigo_turma.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.codigo_turma.setText("")
        self.codigo_turma.setMaxLength(8)
        self.codigo_turma.setClearButtonEnabled(False)
        self.codigo_turma.setObjectName("codigo_turma")
        self.gridLayout_5.addWidget(self.codigo_turma, 2, 3, 1, 4)
        self.data_ingresso_escola = QtWidgets.QDateEdit(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.data_ingresso_escola.setFont(font)
        self.data_ingresso_escola.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.data_ingresso_escola.setCalendarPopup(True)
        self.data_ingresso_escola.setObjectName("data_ingresso_escola")
        self.gridLayout_5.addWidget(self.data_ingresso_escola, 1, 1, 1, 1)
        self.ano_letivo = QtWidgets.QLineEdit(parent=self.InformacoesdeMatricula)
        self.ano_letivo.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ano_letivo.setFont(font)
        self.ano_letivo.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.ano_letivo.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.ano_letivo.setText("")
        self.ano_letivo.setMaxLength(4)
        self.ano_letivo.setClearButtonEnabled(False)
        self.ano_letivo.setObjectName("ano_letivo")
        self.gridLayout_5.addWidget(self.ano_letivo, 2, 7, 1, 1)
        self.data_matricula = QtWidgets.QDateEdit(parent=self.InformacoesdeMatricula)
        self.data_matricula.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.data_matricula.setFont(font)
        self.data_matricula.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.data_matricula.setCalendarPopup(True)
        self.data_matricula.setObjectName("data_matricula")
        self.gridLayout_5.addWidget(self.data_matricula, 1, 4, 1, 2)
        self.matricula = QtWidgets.QLineEdit(parent=self.InformacoesdeMatricula)
        self.matricula.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.matricula.setFont(font)
        self.matricula.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.matricula.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.matricula.setText("")
        self.matricula.setMaxLength(8)
        self.matricula.setClearButtonEnabled(False)
        self.matricula.setObjectName("matricula")
        self.gridLayout_5.addWidget(self.matricula, 1, 6, 1, 2)
        self.data_matricula_label = QtWidgets.QLabel(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.data_matricula_label.setFont(font)
        self.data_matricula_label.setWordWrap(True)
        self.data_matricula_label.setObjectName("data_matricula_label")
        self.gridLayout_5.addWidget(self.data_matricula_label, 1, 2, 1, 2)
        self.data_ingresso_label = QtWidgets.QLabel(parent=self.InformacoesdeMatricula)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(10)
        self.data_ingresso_label.setFont(font)
        self.data_ingresso_label.setWordWrap(True)
        self.data_ingresso_label.setObjectName("data_ingresso_label")
        self.gridLayout_5.addWidget(self.data_ingresso_label, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.InformacoesdeMatricula)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nome_pai = QtWidgets.QLineEdit(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_pai.setFont(font)
        self.nome_pai.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.nome_pai.setMaxLength(255)
        self.nome_pai.setClearButtonEnabled(True)
        self.nome_pai.setObjectName("nome_pai")
        self.verticalLayout_5.addWidget(self.nome_pai)
        self.nome_mae = QtWidgets.QLineEdit(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_mae.setFont(font)
        self.nome_mae.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.nome_mae.setMaxLength(255)
        self.nome_mae.setClearButtonEnabled(True)
        self.nome_mae.setObjectName("nome_mae")
        self.verticalLayout_5.addWidget(self.nome_mae)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.transtorno_global_desenvolvimento = QtWidgets.QGroupBox(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.transtorno_global_desenvolvimento.setFont(font)
        self.transtorno_global_desenvolvimento.setStyleSheet("\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.transtorno_global_desenvolvimento.setObjectName("transtorno_global_desenvolvimento")
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.transtorno_global_desenvolvimento)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 25, 251, 96))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.layoutWidget_3.setFont(font)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.def_autismo = QtWidgets.QCheckBox(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_autismo.setFont(font)
        self.def_autismo.setObjectName("def_autismo")
        self.verticalLayout_8.addWidget(self.def_autismo)
        self.def_rett = QtWidgets.QCheckBox(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_rett.setFont(font)
        self.def_rett.setObjectName("def_rett")
        self.verticalLayout_8.addWidget(self.def_rett)
        self.def_asperger = QtWidgets.QCheckBox(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_asperger.setFont(font)
        self.def_asperger.setObjectName("def_asperger")
        self.verticalLayout_8.addWidget(self.def_asperger)
        self.def_TDI = QtWidgets.QCheckBox(parent=self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_TDI.setFont(font)
        self.def_TDI.setObjectName("def_TDI")
        self.verticalLayout_8.addWidget(self.def_TDI)
        self.gridLayout_6.addWidget(self.transtorno_global_desenvolvimento, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.groupBox_8.setObjectName("groupBox_8")
        self.altas_habilidades = QtWidgets.QCheckBox(parent=self.groupBox_8)
        self.altas_habilidades.setGeometry(QtCore.QRect(10, 57, 216, 19))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.altas_habilidades.setFont(font)
        self.altas_habilidades.setObjectName("altas_habilidades")
        self.gridLayout_6.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.deficiencias = QtWidgets.QGroupBox(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.deficiencias.setFont(font)
        self.deficiencias.setStyleSheet("\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.deficiencias.setObjectName("deficiencias")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.deficiencias)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.def_baixa_visao = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_baixa_visao.setFont(font)
        self.def_baixa_visao.setObjectName("def_baixa_visao")
        self.verticalLayout_7.addWidget(self.def_baixa_visao)
        self.def_cegueira = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_cegueira.setFont(font)
        self.def_cegueira.setObjectName("def_cegueira")
        self.verticalLayout_7.addWidget(self.def_cegueira)
        self.def_auditiva = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_auditiva.setFont(font)
        self.def_auditiva.setObjectName("def_auditiva")
        self.verticalLayout_7.addWidget(self.def_auditiva)
        self.def_intelectual = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_intelectual.setFont(font)
        self.def_intelectual.setObjectName("def_intelectual")
        self.verticalLayout_7.addWidget(self.def_intelectual)
        self.def_fisica = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_fisica.setFont(font)
        self.def_fisica.setObjectName("def_fisica")
        self.verticalLayout_7.addWidget(self.def_fisica)
        self.def_multipla = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_multipla.setFont(font)
        self.def_multipla.setObjectName("def_multipla")
        self.verticalLayout_7.addWidget(self.def_multipla)
        self.def_down = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_down.setFont(font)
        self.def_down.setObjectName("def_down")
        self.verticalLayout_7.addWidget(self.def_down)
        self.def_surdez = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_surdez.setFont(font)
        self.def_surdez.setObjectName("def_surdez")
        self.verticalLayout_7.addWidget(self.def_surdez)
        self.def_surdocegueira = QtWidgets.QCheckBox(parent=self.deficiencias)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.def_surdocegueira.setFont(font)
        self.def_surdocegueira.setObjectName("def_surdocegueira")
        self.verticalLayout_7.addWidget(self.def_surdocegueira)
        self.gridLayout_6.addWidget(self.deficiencias, 0, 1, 2, 1)
        self.verticalLayout_6.addWidget(self.frame)
        self.caixa_endereco = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.caixa_endereco.setFont(font)
        self.caixa_endereco.setObjectName("caixa_endereco")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.caixa_endereco)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.CEP = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        self.CEP.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CEP.setFont(font)
        self.CEP.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.CEP.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.CEP.setText("")
        self.CEP.setMaxLength(8)
        self.CEP.setClearButtonEnabled(False)
        self.CEP.setObjectName("CEP")
        self.gridLayout_7.addWidget(self.CEP, 1, 5, 1, 1)
        self.complemento = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.complemento.setFont(font)
        self.complemento.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.complemento.setMaxLength(10)
        self.complemento.setClearButtonEnabled(False)
        self.complemento.setObjectName("complemento")
        self.gridLayout_7.addWidget(self.complemento, 1, 3, 1, 1)
        self.lab_zona = QtWidgets.QLabel(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        self.lab_zona.setFont(font)
        self.lab_zona.setObjectName("lab_zona")
        self.gridLayout_7.addWidget(self.lab_zona, 4, 0, 1, 1)
        self.numero = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.numero.setFont(font)
        self.numero.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.numero.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.numero.setText("")
        self.numero.setMaxLength(255)
        self.numero.setClearButtonEnabled(False)
        self.numero.setObjectName("numero")
        self.gridLayout_7.addWidget(self.numero, 1, 0, 1, 1)
        self.municipio_endereco = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.municipio_endereco.setFont(font)
        self.municipio_endereco.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.municipio_endereco.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.municipio_endereco.setText("")
        self.municipio_endereco.setMaxLength(30)
        self.municipio_endereco.setClearButtonEnabled(False)
        self.municipio_endereco.setObjectName("municipio_endereco")
        self.gridLayout_7.addWidget(self.municipio_endereco, 3, 0, 1, 3)
        self.bairro_endereco = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bairro_endereco.setFont(font)
        self.bairro_endereco.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.bairro_endereco.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.bairro_endereco.setText("")
        self.bairro_endereco.setMaxLength(32)
        self.bairro_endereco.setClearButtonEnabled(False)
        self.bairro_endereco.setObjectName("bairro_endereco")
        self.gridLayout_7.addWidget(self.bairro_endereco, 3, 3, 1, 2)
        self.uf_endereco = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        self.uf_endereco.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.uf_endereco.setFont(font)
        self.uf_endereco.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.uf_endereco.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.uf_endereco.setText("")
        self.uf_endereco.setMaxLength(2)
        self.uf_endereco.setClearButtonEnabled(False)
        self.uf_endereco.setObjectName("uf_endereco")
        self.gridLayout_7.addWidget(self.uf_endereco, 3, 5, 1, 1)
        self.endereco = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.endereco.setFont(font)
        self.endereco.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.endereco.setMaxLength(255)
        self.endereco.setClearButtonEnabled(True)
        self.endereco.setObjectName("endereco")
        self.gridLayout_7.addWidget(self.endereco, 0, 0, 1, 6)
        self.sel_zona = QtWidgets.QComboBox(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sel_zona.setFont(font)
        self.sel_zona.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.sel_zona.setObjectName("sel_zona")
        self.sel_zona.addItem("")
        self.sel_zona.addItem("")
        self.sel_zona.addItem("")
        self.gridLayout_7.addWidget(self.sel_zona, 5, 0, 1, 2)
        self.telefone = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        self.telefone.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.telefone.setFont(font)
        self.telefone.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.telefone.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.telefone.setText("")
        self.telefone.setMaxLength(13)
        self.telefone.setClearButtonEnabled(False)
        self.telefone.setObjectName("telefone")
        self.gridLayout_7.addWidget(self.telefone, 5, 3, 1, 1)
        self.email = QtWidgets.QLineEdit(parent=self.caixa_endereco)
        font = QtGui.QFont()
        font.setFamily("Inter Medium")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: rgb(243, 230, 213); \n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 2px;\n"
"border-color: rgb(203, 132, 0);\n"
"font: 12px \"Inter Medium\" ;\n"
"color: black\n"
"\n"
"")
        self.email.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly|QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.email.setText("")
        self.email.setMaxLength(25)
        self.email.setClearButtonEnabled(False)
        self.email.setObjectName("email")
        self.gridLayout_7.addWidget(self.email, 5, 5, 1, 1)
        self.verticalLayout_6.addWidget(self.caixa_endereco)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.confirm_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(580, 640, 136, 71))
        self.confirm_button.setStyleSheet("background-color: rgb(203, 132, 0);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(243, 230, 213);\n"
"")
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(440, 640, 136, 71))
        self.cancel_button.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(203, 132, 0)")
        self.cancel_button.setObjectName("cancel_button")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 20, 621, 70))
        self.label.setStyleSheet("font: 57 40pt \"Trend Slab Four\";\n"
"color: rgb(203, 132, 0)")
        self.label.setObjectName("label")
        self.confirm_button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirm_button_2.setGeometry(QtCore.QRect(40, 640, 136, 71))
        self.confirm_button_2.setStyleSheet("background-color: rgb(203, 132, 0);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(243, 230, 213);\n"
"")
        self.confirm_button_2.setObjectName("confirm_button_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UI_Cadastro_Aluno"))
        self.id_aluno.setTitle(_translate("MainWindow", "Identificação do Aluno"))
        self.nome_aluno.setText(_translate("MainWindow", "teste1251"))
        self.nome_aluno.setPlaceholderText(_translate("MainWindow", "Nome do Aluno"))
        self.codigo_NIS.setPlaceholderText(_translate("MainWindow", "NIS"))
        self.label_id_racial.setText(_translate("MainWindow", "Identidade Racial"))
        self.sel_id_racial.setItemText(0, _translate("MainWindow", "Branca"))
        self.sel_id_racial.setItemText(1, _translate("MainWindow", "Preta"))
        self.sel_id_racial.setItemText(2, _translate("MainWindow", "Parda"))
        self.sel_id_racial.setItemText(3, _translate("MainWindow", "Amarela"))
        self.sel_id_racial.setItemText(4, _translate("MainWindow", "Indígena"))
        self.sel_id_racial.setItemText(5, _translate("MainWindow", "N/A"))
        self.label_sexo.setText(_translate("MainWindow", "Sexo*"))
        self.sel_sexo.setItemText(0, _translate("MainWindow", "Masculino"))
        self.sel_sexo.setItemText(1, _translate("MainWindow", "Feminino"))
        self.sel_sexo.setItemText(2, _translate("MainWindow", "N/A"))
        self.nascimento_uf.setPlaceholderText(_translate("MainWindow", "UF*"))
        self.nascimento_municipio.setPlaceholderText(_translate("MainWindow", "Município de nascimento*"))
        self.label_certidao_civil.setText(_translate("MainWindow", "Tipo da Certidão Civil"))
        self.sel_certidao_civil.setItemText(0, _translate("MainWindow", "Nascimento"))
        self.sel_certidao_civil.setItemText(1, _translate("MainWindow", "Casamento"))
        self.sel_certidao_civil.setItemText(2, _translate("MainWindow", "N/A"))
        self.certidao_antiga.setTitle(_translate("MainWindow", "Certidão Modelo Antigo"))
        self.numero_termo.setPlaceholderText(_translate("MainWindow", "Numero Termo"))
        self.livro.setPlaceholderText(_translate("MainWindow", "Livro"))
        self.folha.setPlaceholderText(_translate("MainWindow", "Folha"))
        self.label_data_exp_certidao.setText(_translate("MainWindow", "Data de Expedição"))
        self.data_expedicao.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.certidao_nova.setTitle(_translate("MainWindow", "Certidão Modelo Novo"))
        self.numero_registro_civil.setPlaceholderText(_translate("MainWindow", "Numero de Matrícula (Registro Civil)"))
        self.info_documentos.setTitle(_translate("MainWindow", "Informações Documentadas"))
        self.label_data_exp_info_doc.setText(_translate("MainWindow", "Data de Expedição"))
        self.cpf_aluno.setPlaceholderText(_translate("MainWindow", "Cadastro de Pessoa Física (CPF)"))
        self.documento_tipo.setPlaceholderText(_translate("MainWindow", "Identidade, Documento Estrangerio ou Passaporte"))
        self.data_exp.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.cartorio_nome.setPlaceholderText(_translate("MainWindow", "Nome do Cartório"))
        self.cartorio_uf.setPlaceholderText(_translate("MainWindow", "UF - Cartório"))
        self.documento_orgao_emissor.setPlaceholderText(_translate("MainWindow", "Orgão Emissor"))
        self.cartorio_municipio.setPlaceholderText(_translate("MainWindow", "Município do Cartório"))
        self.InformacoesdeMatricula.setTitle(_translate("MainWindow", "Informações de Matricula"))
        self.nome_escola.setPlaceholderText(_translate("MainWindow", "Nome da Escola"))
        self.serie_label.setText(_translate("MainWindow", "Série*"))
        self.procedencia_label.setText(_translate("MainWindow", "Codigo de Procedência*"))
        self.bolsa_familia.setText(_translate("MainWindow", "Programa Bolsa Família"))
        self.sel_serie.setItemText(0, _translate("MainWindow", "01. Berçário I"))
        self.sel_serie.setItemText(1, _translate("MainWindow", "02. Berçário II"))
        self.sel_serie.setItemText(2, _translate("MainWindow", "03. Maternal I"))
        self.sel_serie.setItemText(3, _translate("MainWindow", "04. Maternal II"))
        self.sel_serie.setItemText(4, _translate("MainWindow", "05. Jardim I"))
        self.sel_serie.setItemText(5, _translate("MainWindow", "06. Jardim II"))
        self.sel_serie.setItemText(6, _translate("MainWindow", "07. Ciclo I - 1° Ano"))
        self.sel_serie.setItemText(7, _translate("MainWindow", "08. Ciclo I - 2° Ano"))
        self.sel_serie.setItemText(8, _translate("MainWindow", "09. Ciclo I - 3° Ano"))
        self.sel_serie.setItemText(9, _translate("MainWindow", "10. Ciclo II - 1° Ano"))
        self.sel_serie.setItemText(10, _translate("MainWindow", "11. Ciclo II - 2° Ano"))
        self.sel_serie.setItemText(11, _translate("MainWindow", "12. Ciclo III - 1° Ano"))
        self.sel_serie.setItemText(12, _translate("MainWindow", "13. Ciclo III - 2° Ano"))
        self.sel_serie.setItemText(13, _translate("MainWindow", "14. Ciclo IV - 1° Ano"))
        self.sel_serie.setItemText(14, _translate("MainWindow", "15. Ciclo IV - 2° Ano"))
        self.sel_serie.setItemText(15, _translate("MainWindow", "16. 1ª Totalidade"))
        self.sel_serie.setItemText(16, _translate("MainWindow", "17.  2ª Totalidade"))
        self.sel_serie.setItemText(17, _translate("MainWindow", "18.  3ª Etapa"))
        self.sel_serie.setItemText(18, _translate("MainWindow", "19.  4ª Etapa"))
        self.sel_serie.setItemText(19, _translate("MainWindow", "20. 1° Ano"))
        self.sel_serie.setItemText(20, _translate("MainWindow", "21. 2° Ano"))
        self.sel_serie.setItemText(21, _translate("MainWindow", "22. 3° Ano"))
        self.sel_serie.setItemText(22, _translate("MainWindow", "23. 4° Ano"))
        self.turno_label.setText(_translate("MainWindow", "Turno*"))
        self.transporte.setText(_translate("MainWindow", "Transporte Escolar?"))
        self.sel_turno.setItemText(0, _translate("MainWindow", "Manhã"))
        self.sel_turno.setItemText(1, _translate("MainWindow", "Intermediário"))
        self.sel_turno.setItemText(2, _translate("MainWindow", "Tarde"))
        self.sel_turno.setItemText(3, _translate("MainWindow", "Noite"))
        self.sel_turno.setItemText(4, _translate("MainWindow", "Tempo Integral"))
        self.sel_procedencia.setItemText(0, _translate("MainWindow", "01 - Do Lar"))
        self.sel_procedencia.setItemText(1, _translate("MainWindow", "02 - Escola Municipal"))
        self.sel_procedencia.setItemText(2, _translate("MainWindow", "03 - Escola Estadual"))
        self.sel_procedencia.setItemText(3, _translate("MainWindow", "04 - Escola Particular"))
        self.sel_procedencia.setItemText(4, _translate("MainWindow", "05 - Escola Federal"))
        self.sel_procedencia.setItemText(5, _translate("MainWindow", "06 - Escola Comunitária"))
        self.codigo_inep.setPlaceholderText(_translate("MainWindow", "Codigo Senso Inep*"))
        self.codigo_turma.setPlaceholderText(_translate("MainWindow", "Codigo Turma*"))
        self.data_ingresso_escola.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.ano_letivo.setPlaceholderText(_translate("MainWindow", "Ano Letivo*"))
        self.data_matricula.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.matricula.setPlaceholderText(_translate("MainWindow", "Matricula*"))
        self.data_matricula_label.setText(_translate("MainWindow", "Data de Matricula"))
        self.data_ingresso_label.setText(_translate("MainWindow", "Data de Ingresso"))
        self.groupBox.setTitle(_translate("MainWindow", "Dados dos Pais/Responsáveis"))
        self.nome_pai.setPlaceholderText(_translate("MainWindow", "Nome do Pai"))
        self.nome_mae.setPlaceholderText(_translate("MainWindow", "Nome da Mãe"))
        self.transtorno_global_desenvolvimento.setTitle(_translate("MainWindow", "Transtorno Global do Desenvolvimento"))
        self.def_autismo.setText(_translate("MainWindow", "Autismo"))
        self.def_rett.setText(_translate("MainWindow", "Sindrome de Rett"))
        self.def_asperger.setText(_translate("MainWindow", "Sindrome de Asperger"))
        self.def_TDI.setText(_translate("MainWindow", "Transtorno desintegrativo da infância"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Altas Habilidades / Superdotação"))
        self.altas_habilidades.setText(_translate("MainWindow", "Altas Habilidades / Superdotação"))
        self.deficiencias.setTitle(_translate("MainWindow", "Deficiências"))
        self.def_baixa_visao.setText(_translate("MainWindow", "Baixa Visão"))
        self.def_cegueira.setText(_translate("MainWindow", "Cegueira"))
        self.def_auditiva.setText(_translate("MainWindow", "Deficiência Auditiva"))
        self.def_intelectual.setText(_translate("MainWindow", "Deficiência Intelectual"))
        self.def_fisica.setText(_translate("MainWindow", "Deficiência Física"))
        self.def_multipla.setText(_translate("MainWindow", "Deficiência Múltipla"))
        self.def_down.setText(_translate("MainWindow", "Sindrome de Down"))
        self.def_surdez.setText(_translate("MainWindow", "Surdez"))
        self.def_surdocegueira.setText(_translate("MainWindow", "Surdocegueira"))
        self.caixa_endereco.setTitle(_translate("MainWindow", "Endereço"))
        self.CEP.setPlaceholderText(_translate("MainWindow", "CEP*"))
        self.complemento.setPlaceholderText(_translate("MainWindow", "Complemento"))
        self.lab_zona.setText(_translate("MainWindow", "Zona*"))
        self.numero.setPlaceholderText(_translate("MainWindow", "N°"))
        self.municipio_endereco.setPlaceholderText(_translate("MainWindow", "Município*"))
        self.bairro_endereco.setPlaceholderText(_translate("MainWindow", "Bairro"))
        self.uf_endereco.setPlaceholderText(_translate("MainWindow", "UF"))
        self.endereco.setPlaceholderText(_translate("MainWindow", "Endereço"))
        self.sel_zona.setItemText(0, _translate("MainWindow", "Rural"))
        self.sel_zona.setItemText(1, _translate("MainWindow", "Urbana"))
        self.sel_zona.setItemText(2, _translate("MainWindow", "N/A"))
        self.telefone.setPlaceholderText(_translate("MainWindow", "Telefone"))
        self.email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.confirm_button.setText(_translate("MainWindow", "Confirmar"))
        self.cancel_button.setText(_translate("MainWindow", "Cancelar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Atualizar perfil</p></body></html>"))
        self.confirm_button_2.setText(_translate("MainWindow", "Deletar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
