# Form implementation generated from reading ui file '.\editar_matricula.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 720)
        MainWindow.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.confirm_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(676, 40, 136, 71))
        self.confirm_button.setStyleSheet("background-color: rgb(203, 132, 0);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(243, 230, 213);\n"
"")
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(530, 40, 136, 71))
        self.cancel_button.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(203, 132, 0)")
        self.cancel_button.setObjectName("cancel_button")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(160, 30, 341, 101))
        font = QtGui.QFont()
        font.setFamily("Trend Slab Four")
        font.setPointSize(48)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(203, 132, 0)")
        self.title_label.setObjectName("title_label")
        self.refresh_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(520, 150, 136, 41))
        self.refresh_button.setStyleSheet("background-color: rgb(203, 132, 0);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(243, 230, 213);\n"
"")
        self.refresh_button.setObjectName("refresh_button")
        self.turma_selection = QtWidgets.QComboBox(parent=self.centralwidget)
        self.turma_selection.setGeometry(QtCore.QRect(230, 150, 261, 41))
        self.turma_selection.setStyleSheet("background-color:rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px  \"Inter Black\" ;\n"
"padding: 6px;\n"
"color: rgb(203, 132, 0);\n"
"alternate-background-color:rgb(243, 230, 213);")
        self.turma_selection.setEditable(True)
        self.turma_selection.setObjectName("turma_selection")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.turma_selection.addItem("")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(130, 210, 721, 451))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lista_alunos = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        self.lista_alunos.setObjectName("lista_alunos")
        self.horizontalLayout.addWidget(self.lista_alunos)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.confirm_button.setText(_translate("MainWindow", "Confirmar"))
        self.cancel_button.setText(_translate("MainWindow", "Cancelar"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p>alunos</p></body></html>"))
        self.refresh_button.setText(_translate("MainWindow", "Atualizar"))
        self.turma_selection.setItemText(0, _translate("MainWindow", "01. Berçário I"))
        self.turma_selection.setItemText(1, _translate("MainWindow", "02. Berçário II"))
        self.turma_selection.setItemText(2, _translate("MainWindow", "03. Maternal I"))
        self.turma_selection.setItemText(3, _translate("MainWindow", "04. Maternal II"))
        self.turma_selection.setItemText(4, _translate("MainWindow", "05. Jardim I"))
        self.turma_selection.setItemText(5, _translate("MainWindow", "06. Jardim II"))
        self.turma_selection.setItemText(6, _translate("MainWindow", "07. Ciclo I - 1° Ano"))
        self.turma_selection.setItemText(7, _translate("MainWindow", "08. Ciclo I - 2° Ano"))
        self.turma_selection.setItemText(8, _translate("MainWindow", "09. Ciclo I - 3° Ano"))
        self.turma_selection.setItemText(9, _translate("MainWindow", "10. Ciclo II - 1° Ano"))
        self.turma_selection.setItemText(10, _translate("MainWindow", "11. Ciclo II - 2° Ano"))
        self.turma_selection.setItemText(11, _translate("MainWindow", "12. Ciclo III - 1° Ano"))
        self.turma_selection.setItemText(12, _translate("MainWindow", "13. Ciclo III - 2° Ano"))
        self.turma_selection.setItemText(13, _translate("MainWindow", "14. Ciclo IV - 1° Ano"))
        self.turma_selection.setItemText(14, _translate("MainWindow", "15. Ciclo IV - 2° Ano"))
        self.turma_selection.setItemText(15, _translate("MainWindow", "16. 1ª Totalidade"))
        self.turma_selection.setItemText(16, _translate("MainWindow", "17.  2ª Totalidade"))
        self.turma_selection.setItemText(17, _translate("MainWindow", "18.  3ª Etapa"))
        self.turma_selection.setItemText(18, _translate("MainWindow", "19.  4ª Etapa"))
        self.turma_selection.setItemText(19, _translate("MainWindow", "20. 1° Ano"))
        self.turma_selection.setItemText(20, _translate("MainWindow", "21. 2° Ano"))
        self.turma_selection.setItemText(21, _translate("MainWindow", "22. 3° Ano"))
        self.turma_selection.setItemText(22, _translate("MainWindow", "23. 4° Ano"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
