# Form implementation generated from reading ui file 'frequencia_screen.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UI_FrequenciaWindow(object):
    def setupUi(self, FrequenciaWindow):
        FrequenciaWindow.setObjectName("FrequenciaWindow")
        FrequenciaWindow.resize(1280, 720)
        FrequenciaWindow.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=FrequenciaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lista_freq = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lista_freq.setGeometry(QtCore.QRect(40, 150, 550, 530))
        self.lista_freq.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 14px\"Inter Medium\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(131, 3, 2);")
        self.lista_freq.setObjectName("lista_freq")
        self.obs_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.obs_label.setGeometry(QtCore.QRect(600, 380, 640, 42))
        font = QtGui.QFont()
        font.setFamily("Trend Slab Four")
        font.setPointSize(48)
        self.obs_label.setFont(font)
        self.obs_label.setStyleSheet("color: rgb(130, 3, 0);")
        self.obs_label.setObjectName("obs_label")
        self.obs_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.obs_text.setGeometry(QtCore.QRect(600, 428, 640, 252))
        self.obs_text.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 14px\"Inter Medium\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(131, 3, 2);")
        self.obs_text.setObjectName("obs_text")
        self.confirm_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(1104, 50, 136, 71))
        self.confirm_button.setStyleSheet("background-color: rgb(131, 3, 2);;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(243, 230, 213);\n"
"")
        self.confirm_button.setObjectName("confirm_button")
        self.cancel_button = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: FrequenciaWindow.close())
        self.cancel_button.setGeometry(QtCore.QRect(958, 50, 136, 71))
        self.cancel_button.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(131, 3, 2);")
        self.cancel_button.setObjectName("cancel_button")
        self.just_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.just_label.setGeometry(QtCore.QRect(600, 150, 640, 42))
        font = QtGui.QFont()
        font.setFamily("Trend Slab Four")
        font.setPointSize(48)
        self.just_label.setFont(font)
        self.just_label.setStyleSheet("color: rgb(130, 3, 0);")
        self.just_label.setWordWrap(True)
        self.just_label.setObjectName("just_label")
        self.just_caixa = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.just_caixa.setGeometry(QtCore.QRect(600, 197, 640, 168))
        self.just_caixa.setStyleSheet("background-color: rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 14px\"Inter Medium\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(131, 3, 2);")
        self.just_caixa.setObjectName("just_caixa")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(383, 40, 513, 84))
        font = QtGui.QFont()
        font.setFamily("Trend Slab Four")
        font.setPointSize(48)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(130, 3, 0);")
        self.title_label.setObjectName("title_label")
        self.date_selection = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_selection.setGeometry(QtCore.QRect(40, 40, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Inter Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.date_selection.setFont(font)
        self.date_selection.setStyleSheet("background-color:rgb(243, 230, 213);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"font:bold 20px  \"Inter Black\" ;\n"
"min-width: 5em;\n"
"padding: 6px;\n"
"color: rgb(130, 3, 0);\n"
"alternate-background-color:rgb(243, 230, 213);")
        self.date_selection.setWrapping(False)
        self.date_selection.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.date_selection.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.date_selection.setCalendarPopup(True)
        self.date_selection.setObjectName("date_selection")
        FrequenciaWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrequenciaWindow)
        QtCore.QMetaObject.connectSlotsByName(FrequenciaWindow)

    def retranslateUi(self, FrequenciaWindow):
        _translate = QtCore.QCoreApplication.translate
        FrequenciaWindow.setWindowTitle(_translate("FrequenciaWindow", "FrequenciaWindow"))
        self.obs_label.setText(_translate("FrequenciaWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">observações</span></p></body></html>"))
        self.confirm_button.setText(_translate("FrequenciaWindow", "Confirmar"))
        self.cancel_button.setText(_translate("FrequenciaWindow", "Cancelar"))
        self.just_label.setText(_translate("FrequenciaWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Justificativa de faltas</span></p></body></html>"))
        self.title_label.setText(_translate("FrequenciaWindow", "<html><head/><body><p>frequência</p></body></html>"))
        self.date_selection.setDisplayFormat(_translate("FrequenciaWindow", "d/M/yyyy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UI_FrequenciaWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
